style(chezmoi): newlines, quotes, trailing spaces

diff --git a/root/.chezmoiscripts/run_onchange_after_post_install_yadr.sh.tmpl b/root/.chezmoiscripts/run_onchange_after_post_install_yadr.sh.tmpl
--- a/root/.chezmoiscripts/run_onchange_after_post_install_yadr.sh.tmpl
+++ b/root/.chezmoiscripts/run_onchange_after_post_install_yadr.sh.tmpl
@@ -1,17 +1,18 @@
-  {{- if eq .chezmoi.os "linux" "darwin" -}}
+{{- if eq .chezmoi.os "linux" "darwin" -}}
 #!/usr/bin/env bash
 
+set -e # -e: exit on error
 
-    {{- if lookPath "zsh" }}
+  {{- if lookPath "zsh" }}
 
 chsh --shell /bin/zsh
 
-    {{- else }}
+  {{- else }}
 
 echo 'Install zsh, then run:'
 echo '  $ chezmoi apply --source-path {{ joinPath .chezmoi.sourceDir .chezmoi.sourceFile }}'
 
-    {{- end }}
+  {{- end }}
 
 exit 0
-  {{- end -}}
+{{- end }}
